# Generated by Django 2.2.7 on 2019-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField()),
                ('edad', models.IntegerField()),
                ('nivelEstudios', models.CharField(choices=[('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Bachillerato'), ('4', 'Licenciatura'), ('5', 'Especialidad'), ('6', 'Maestria'), ('7', 'Doctorado'), ('9', 'Post-Doctorado')], max_length=1)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1)),
                ('nivelAcceso', models.CharField(choices=[('E', 'Estudiante'), ('C', 'Catedratico'), ('A', 'Administrativo')], max_length=1)),
                ('passwd', models.CharField(max_length=150)),
            ],
        ),
    ]
