# Generated by Django 2.2.7 on 2019-11-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('areamaestro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('cubiculo', models.CharField(max_length=50)),
                ('numeroTrabajdor', models.CharField(max_length=13)),
                ('estatus', models.CharField(max_length=2)),
                ('areaExpertise', models.ForeignKey(help_text='Seleccione un Área', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maestroAreaExpertise', to='areamaestro.AreaMaestro')),
            ],
            bases=('personas.persona',),
        ),
    ]
