# Generated by Django 2.2.7 on 2019-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('ST', 'Suspendido'), ('P', 'Permiso'), ('SD', 'Suspendido Definitivo')], max_length=2),
        ),
    ]
