# Generated by Django 2.2.7 on 2019-11-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('matricula', models.CharField(max_length=13)),
                ('semestre', models.CharField(choices=[('1', '1er Semestre'), ('2', '2do Semestre'), ('3', '3er Semestre'), ('4', '4to Semestre'), ('5', '5nto Semestre'), ('6', '6to Semestre'), ('7', '7to Semestre'), ('8', '8avo Semestre'), ('9', '9no Semestre'), ('10', '10mo Semestre')], max_length=2)),
                ('numeroMateriasCursando', models.CharField(max_length=2)),
                ('totalNumeroMateriasAprobadas', models.CharField(default=0, max_length=2)),
                ('totalNumerosMateriasReprobadas', models.CharField(default=0, max_length=2)),
            ],
            bases=('personas.persona',),
        ),
    ]
