# Generated by Django 2.2.7 on 2019-11-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaeducativo', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='programaEducativo',
            field=models.ForeignKey(help_text='Seleccione un Programa Educativo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudianteProgramaEducativo', to='programaeducativo.ProgramaEducativo'),
        ),
    ]
