# Generated by Django 2.2.7 on 2019-11-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('numeroAlumnos', models.IntegerField(max_length=2)),
                ('estatus', models.CharField(choices=[('1', 'Alta'), ('2', 'Baja'), ('3', 'Suspendido')], max_length=1)),
                ('materia', models.ForeignKey(help_text='Selecione una Materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruposMaterias', to='materias.Materia')),
            ],
        ),
    ]
