# Generated by Django 2.2.7 on 2019-11-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='numeroAlumnos',
            field=models.CharField(max_length=2),
        ),
    ]
