# Generated by Django 2.2.7 on 2019-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20191120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='numeroAlumnos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
