# Generated by Django 2.2.7 on 2019-11-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areaestudiomateria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estatusMateria', models.CharField(choices=[('1', 'Alta'), ('2', 'Pendiente'), ('3', 'Baja')], max_length=1)),
                ('areaEstudio', models.ForeignKey(help_text='Seleccione una Área de Estudio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiaAreaEstudioMateria', to='areaestudiomateria.AreaEstudioMateria')),
            ],
        ),
    ]
